version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: travel-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel_db
      MYSQL_USER: travel_user
      MYSQL_PASSWORD: travel_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
